#Robocode Compiler Properties
#Tue Jan 27 14:34:19 NZDT 2026
compiler.options=-verbose -encoding UTF-8
robocode.version=1.10.1
compiler.classpath=-classpath libs/robocode.jar\:/home/mcfiec/workspaces/robocode/robots
compiler.binary=javac
