#Robocode window sizes
#Fri Feb 20 14:21:16 NZDT 2026
net.sf.robocode.ui.dialog.ConsoleDialog=2625,533,500,400
net.sf.robocode.ui.dialog.NewBattleDialog=2724,309,840,650
net.sf.robocode.ui.dialog.PreferencesDialog=2692,489,893,340
net.sf.robocode.ui.dialog.RobocodeFrame=2682,308,913,703
net.sf.robocode.ui.dialog.TeamCreator=2396,504,958,503
net.sf.robocode.ui.editor.RobocodeEditor=2036,282,750,613
net.sf.robocode.ui.packager.RobotPackager=2396,504,958,503
